"""added monster.name column for uniqueness

Revision ID: 0370c160cc50
Revises: 860e64d9dee8
Create Date: 2025-06-13 16:34:21.587607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0370c160cc50'
down_revision: Union[str, None] = '860e64d9dee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_species', sa.Column('name', sa.String(), nullable=True))
    with op.batch_alter_table('monster_species') as batch_op:
     batch_op.create_unique_constraint('uq_monster_species_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monster_species', type_='unique')
    op.drop_column('monster_species', 'name')
    # ### end Alembic commands ###
