"""add base_level to monster_species

Revision ID: 17e716196f4b
Revises: db8d06a0a59f
Create Date: 2025-06-16 00:02:27.356634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e716196f4b'
down_revision: Union[str, None] = 'db8d06a0a59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_species', sa.Column('base_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster_species', 'base_level')
    # ### end Alembic commands ###
