"""added association tables

Revision ID: 4d7a88404485
Revises: 81741cc7da72
Create Date: 2025-06-16 21:01:57.803039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7a88404485'
down_revision: Union[str, None] = '81741cc7da72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_association',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], )
    )
    op.create_table('rival_association',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('rival_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['rival_id'], ['players.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rival_association')
    op.drop_table('friend_association')
    # ### end Alembic commands ###
