"""Fix player achievements FK

Revision ID: 81741cc7da72
Revises: 17e716196f4b
Create Date: 2025-06-16 14:17:38.110647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81741cc7da72'
down_revision: Union[str, None] = '17e716196f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_achievements', sa.Column('achievement_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'player_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'player_achievements', 'achievements', ['achievement_id'], ['id'])
    op.drop_column('player_achievements', 'achievement_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_achievements', sa.Column('achievement_name', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'player_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'player_achievements', 'achievements', ['achievement_name'], ['achievement_name'])
    op.drop_column('player_achievements', 'achievement_id')
    # ### end Alembic commands ###
