"""added some columns

Revision ID: d2be1cd7e0c8
Revises: a95fded4bdcc
Create Date: 2025-06-15 18:12:59.216449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2be1cd7e0c8'
down_revision: Union[str, None] = 'a95fded4bdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_monsters', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'money')
    op.drop_column('players', 'xp')
    op.drop_column('players', 'level')
    op.drop_column('player_monsters', 'xp')
    # ### end Alembic commands ###
